#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
   herbstclient "$@"
   # implement chaining here
  # cmds="$cmds , $@"
}

hc emit_hook reload

##########################################################
# General
##########################################################

#Set background image
feh --bg-fill ~/Images/walls/NNZUJrW.jpg

# Read in xmodmap
xmodmap ~/.Xmodmap

#Shit for intellij
wmname LG3D

# remove all existing keybindings
hc keyunbind --all

# Read in monitor layout from arandr
sh ~/.screenlayout/something.sh

# Start gnome-screensaver for lock screen
gnome-screensaver &

# Conky config file 
# dzconky &

# Tags
TAG_NAMES=( "chat" "shell" "dev" "web" "music" "misc"  )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
done

#add Monitors
hc add_monitor 1920x1080+0+0 "chat"
hc add_monitor 1920x1080+1920+0 "shell"
hc move_monitor 0 1920x1080+0+0

# Spacing
hc set frame_gap -20
hc set window_gap 20

##########################################################
# Keybindings
##########################################################

# Change Mod to Super
Mod=Mod4
hc keybind $Mod-Control-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt 
hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-w spawn firefox
hc keybind $Mod-Control-l spawn gnome-screensaver-command -l

# Set 'asd/zxc' to goto tags 1-3/4-6, only in dvorak
hc keybind $Mod-a use "chat"
hc keybind $Mod-o use "shell" 
hc keybind $Mod-e use "dev"
hc keybind $Mod-apostrophe use "web" 
hc keybind $Mod-q use "music" 
hc keybind $Mod-j use "misc" 

# Send application to tag # with F# (tags are zero-indexed)
hc keybind $Mod-F1 move_index 0
hc keybind $Mod-F2 move_index 1
hc keybind $Mod-F3 move_index 2
hc keybind $Mod-F4 move_index 3
hc keybind $Mod-F5 move_index 4
hc keybind $Mod-F6 move_index 5

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 2
hc keybind $Mod-Control-space cycle_layout 1
hc keybind $Mod-k split vertical 0.5
hc keybind $Mod-u split horizontal 0.5
hc keybind $Mod-l floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-comma move_index -1
hc keybind $Mod-period move_index +1

# resizing PANELS
RESIZESTEP=0.025
hc keybind $Mod-Alt-h resize left +$RESIZESTEP
hc keybind $Mod-Alt-n resize down +$RESIZESTEP
hc keybind $Mod-Alt-t resize up +$RESIZESTEP
hc keybind $Mod-Alt-s resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus (hjkl switched to htns for dvorak)
hc keybind $Mod-z spawn focusurgent
hc keybind $Mod-BackSpace use_index +1 --skip-visible
hc keybind $Mod-Shift-BackSpace use_index -1 --skip-visible
hc keybind $Mod-Control-s cycle_monitor
hc keybind $Mod-Control-h cycle_monitor -1
# hc keybind $Mod-Tab         cycle_all +1 don't really use these
# hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-Tab cycle
hc keybind $Mod-h focus left
hc keybind $Mod-n focus down
hc keybind $Mod-t focus up
hc keybind $Mod-s focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-n shift down
hc keybind $Mod-Shift-t shift up
hc keybind $Mod-Shift-s shift right


# Sound keybindings for work
hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+ > /dev/null
hc keybind XF86AudioLowerVolume spawn amixer set Master 5%- > /dev/null
hc keybind XXF86AudioMute spawn amixer set Master toggle

##########################################################
# Colors
##########################################################
hc set frame_border_active_color '#98AFC7'
hc set frame_border_normal_color '#646D7E'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#424140'
hc set frame_border_width 2
hc set window_border_width 2
hc set window_border_normal_color '#848482'
hc set window_border_active_color '#78C7C7'
hc set frame_bg_transparent 1
hc set frame_gap 8

##########################################################
# Rules 
##########################################################

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off


# CHAIN
#herbstclient chain $cmds&

##########################################################
# Panel
##########################################################
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done

