#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#5A8E3A'
feh --bg-fill ~/Images/walls/NNZUJrW.jpg

#fuckcaps n shit
#fuckcaps
xmodmap ~/.Xmodmap


# remove all existing keybindings
hc keyunbind --all


# keybindings
Mod=Mod4
hc keybind $Mod-Control-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt 
hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-w spawn chromium-browser
hc keybind $Mod-Control-l spawn /usr/lib/kde4/libexec/kscreenlocker_greet


# tags
TAG_NAMES=( "chat" "shell" "dev" "web" "music" "misc"  )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
done

#fix Mod-# for programmers dvorak
hc keybind $Mod-ampersand use "chat"
hc keybind $Mod-bracketleft use "shell" 
hc keybind $Mod-braceleft use "dev"
hc keybind $Mod-braceright use "web" 
hc keybind $Mod-parenleft use "music" 
hc keybind $Mod-equal use "misc" 

hc keybind $Mod-percent move "chat"
hc keybind $Mod-7 move_index "shell"
hc keybind $Mod-5 move_index "dev"
hc keybind $Mod-3 move_index "web"
hc keybind $Mod-1 move_index "music"
hc keybind $Mod-9 move_index "misc"

#add Monitors
hc add_monitor 1440x900+0+0 "chat"
hc add_monitor 1920x1080+1440+0 "shell"
hc move_monitor 0 1440x900+0+0

#Shit for intellij
wmname LG3D

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 2
hc keybind $Mod-Control-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-l floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-comma move_index -1
hc keybind $Mod-period move_index +1

# resizing PANELS
RESIZESTEP=0.05
hc keybind $Mod-Alt-h resize left +$RESIZESTEP
hc keybind $Mod-Alt-n resize down +$RESIZESTEP
hc keybind $Mod-Alt-t resize up +$RESIZESTEP
hc keybind $Mod-Alt-s resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-z spawn focusurgent
hc keybind $Mod-BackSpace use_index +1 --skip-visible
hc keybind $Mod-Shift-BackSpace use_index -1 --skip-visible
hc keybind $Mod-Control-s cycle_monitor
hc keybind $Mod-Control-h cycle_monitor -1
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-n focus down
hc keybind $Mod-t focus up
hc keybind $Mod-s focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-n shift down
hc keybind $Mod-Shift-t shift up
hc keybind $Mod-Shift-s shift right

# colors
hc set frame_border_active_color '#98AFC7'
hc set frame_border_normal_color '#646D7E'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#424140'
hc set frame_border_width 2
hc set window_border_width 2
hc set window_border_normal_color '#848482'
hc set window_border_active_color '#78C7C7'
hc set frame_bg_transparent
hc set frame_gap 8

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done
